import time
import os
import sys
from character import Character
from item import Item

class Colors:
    BLACK = '\033[30m'
    RED = '\033[31m'
    GREEN = '\033[32m'
    YELLOW = '\033[33m'
    BLUE = '\033[34m'
    MAGENTA = '\033[35m'
    CYAN = '\033[36m'
    WHITE = '\033[37m'
    BRIGHT_BLACK = '\033[90m'
    BRIGHT_RED = '\033[91m'
    BRIGHT_GREEN = '\033[92m'
    BRIGHT_YELLOW = '\033[93m'
    BRIGHT_BLUE = '\033[94m'
    BRIGHT_MAGENTA = '\033[95m'
    BRIGHT_CYAN = '\033[96m'
    BRIGHT_WHITE = '\033[97m'
    RESET = '\033[0m'  # Resets the color to default

def pause(seconds):
    time.sleep(seconds)

def clear_screen():
    # Check if the system is Windows
    if os.name == 'nt':
        os.system('cls')  # Clear screen for Windows
    else:
        os.system('clear')  # Clear screen for macOS and Linux

# Typewriter effect function (generated by ChatGPT)
def typewriter_effect(text, delay=0.1, color=Colors.RESET):
    for char in text:
        sys.stdout.write(f"{color}{char}{Colors.RESET}")
        sys.stdout.flush()  # Ensures the output is displayed immediately
        time.sleep(delay)
    print()  # Move to the next line after the text is printed

# initial text introduction
print()
typewriter_effect("Welcome to Corner Store Simulator!", delay=0.05, color=Colors.CYAN)
print()

typewriter_effect("A man walks into the corner store late at night and approaches you at the counter....", delay=0.04, color=Colors.BRIGHT_YELLOW)
print()


in_conversation = False
found_lighters = False

# Main game loop
while True:
    # Start conversation loop until valid input ('E' or 'Q') is provided
    while not in_conversation:
        d1 = input("Press 'E' to greet them or 'Q' to flee the conversation: ").lower()
        # generated by ChatGPT because I didn't know how to have it go with the typewriter effect
        player = Character("Man", 100, [], {
            "Hello": ("NPC: Hey, you guys got any lighters here?", Character.Colors.GREEN, 0.04),
            "No": ("YOU: No, but we may have some in the back. I'll go check.", Character.Colors.BLUE, 0.04),
            "Give": ("YOU: I found a pack in the back.", Character.Colors.BLUE, 0.04),
            "Goodbye": ("NPC: Thank you, have a good night!", Character.Colors.GREEN, 0.04)
})
        if d1 == "e":
            # Player starts talking to the NPC
            player.talk_to_player("Hello")
            in_conversation = True  # Now the conversation starts
        elif d1 == "q":
            # Exits the conversation
            typewriter_effect("You walked away, pretending you needed to pee.", delay=0.05, color=Colors.RED)
            break
        else:
            # Handle invalid input and loop back to ask for valid input
            typewriter_effect("Invalid Input. Press 'E' or 'Q'.", delay=0.04, color=Character.Colors.RED)
            print()

    # Once in the conversation, proceed to this part
    if in_conversation:
        typewriter_effect("You look behind you at the counter, but don't see any lighters.", delay=0.04, color=Character.Colors.YELLOW)
        d2 = input("Press 'E' to reply or 'Q' to flee the conversation: ").lower()

        # Conversation choices
        if d2 == "e":
            player.talk_to_player("No")  # Player's response: "No, but we may have some in the back"
            print()
            typewriter_effect("You walk into the backroom but don't know where to look. Left or Right?", delay=0.04, color=Character.Colors.BRIGHT_YELLOW)

            # Loop to find lighters
            while not found_lighters:
                d2 = input("Press 'L' for left or 'R' for right: ").lower()
                if d2 == "l":
                    lighters = Item("Lighters", "A pack of lighters", 0)
                    player.inventory.append(lighters)
                    typewriter_effect("You find a pack of lighters next to the rat's nest in the corner and pick them up.", delay=0.04, color=Character.Colors.BRIGHT_YELLOW)
                    found_lighters = True  # Player found the lighters, breaking the loop
                    print() 
                elif d2 == "r":
                    typewriter_effect("You don't find any lighters and turn back.", delay=0.04, color=Character.Colors.BRIGHT_YELLOW)
                    print()
                    typewriter_effect("You're back in the backroom. Left or Right?", delay=0.04, color=Character.Colors.BRIGHT_YELLOW)
                else:
                    # Stay in this loop until valid input is given
                    typewriter_effect("Invalid Input. Press 'L' or 'R'.", delay=0.04, color=Character.Colors.RED)
                    print()

        elif d2 == "q":
            typewriter_effect("You walked away, pretending you needed to pee.", delay=0.05, color=Character.Colors.RED)
            break

        else:
            # Stay in this loop until valid input is given
            typewriter_effect("Invalid Input. Press 'E' or 'Q'.", delay=0.04, color=Character.Colors.RED)
            print()

    # After the lighters are found, give the player a choice to give them to the NPC
    if found_lighters:
        while True:  # Loop until valid input or break
            d3 = input("Press 'G' to give the lighters to the man or 'Q' to flee: ").lower()
            # Giving the lighters to the man
            if d3 == "g":
                if lighters in player.inventory:
                    player.inventory.remove(lighters)  # Remove the lighters from the player's inventory
                    player.talk_to_player("Give")
                    typewriter_effect("You gave the lighters to the man. He gives you his thanks and pays.", delay=0.04, color=Character.Colors.YELLOW)
                    print()
                    # Loop until valid goodbye input
                    while True:
                        d3a = input("Press 'E' to say goodbye: ").lower()
                        if d3a == "e":
                            player.talk_to_player("Goodbye")
                            typewriter_effect("The man walks out of the store.", delay=0.04, color=Character.Colors.YELLOW)
                            break  # End the game
                        else:
                            typewriter_effect("Invalid input. Press 'E' to say goodbye.", delay=0.04, color=Character.Colors.RED)
                    break  # Exit the lighters giving loop
                else:
                    typewriter_effect("You don't have any lighters.", delay=0.04, color=Character.Colors.RED)

            elif d3 == "q":
                typewriter_effect("You walked away, pretending you needed to pee.", delay=0.05, color=Character.Colors.RED)
                break  # Exit the game

            else:
                # If the player inputs invalid option, stay in this loop and prompt again
                typewriter_effect("Invalid Input. Press 'G' to give the lighters or 'Q' to flee.", delay=0.04, color=Character.Colors.RED)
        break
    break
print()
typewriter_effect("A few moments after the man leaves, a woman walks in....", delay=0.04, color=Colors.BRIGHT_YELLOW)
print()
d1a = input("Press 'E' to greet them or 'Q' to flee the conversation: ").lower()
player = Character("Woman", 100, [], {
            "Hello": ("NPC: Hi there! Can I have a slushie?", Character.Colors.GREEN, 0.04),
            "Q": ("YOU: Sure, what flavor would you like?.", Character.Colors.BLUE, 0.04),
            "Flavor": ("NPC: Cement flavor please!", Character.Colors.GREEN, 0.04),
            "Order": ("YOU: Alright, give me a few moments to prepare your slushie!", Character.Colors.BLUE, 0.04)
})

if d1a == "e":
    player.talk_to_player("Hello")
    typewriter_effect("You look behind you to ensure the slushie machine is working. It seems to be working fine.", delay=0.04, color=Character.Colors.BRIGHT_YELLOW)
    print()
    d1ab = input("Press 'E' to reply or 'Q' to flee the conversation: ").lower()
    if d1ab == "e":
        player.talk_to_player("Q")
        typewriter_effect("The woman ponders for a moment...", delay=0.03, color=Character.Colors.BRIGHT_YELLOW)
        player.talk_to_player("Flavor")
        print()
        d1ac = input("Press 'E' to reply or 'Q' to flee the conversation: ").lower()
        if d1ac == "e":
            player.talk_to_player("Order")
            print()
            typewriter_effect("You walk to the back of the counter to the slushie machine.", delay=0.04, color=Character.Colors.BRIGHT_YELLOW)
            typewriter_effect("Now you must prepare the slushie for the customer.", delay=0.04, color=Character.Colors.BRIGHT_YELLOW)
            typewriter_effect("To prepare the slushie, you must win a game of Wordle.", delay=0.04, color=Character.Colors.BRIGHT_YELLOW)
            typewriter_effect("Good Luck!", delay=0.04, color=Character.Colors.BRIGHT_YELLOW)
            d1ad = input("Press 'E' to continue: ").lower()
            if d1ad == "e":
                clear_screen()
                from wordle import wordle_game
            else:
                typewriter_effect("Invalid Input. Press 'E' to continue.", delay=0.04, color=Character.Colors.RED)
                print()
